######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 9 21:09:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mymouse.h
FORMS += widget.ui
SOURCES += main.cpp mymouse.cpp
